/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SimRawWrapper */

#ifndef _Included_SimRawWrapper
#define _Included_SimRawWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SimRawWrapper
 * Method:    init
 * Signature: (Ljava/lang/String;LGhdlWaveFormat;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SimRawWrapper_init
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     SimRawWrapper
 * Method:    getHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_SimRawWrapper_getHandle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     SimRawWrapper
 * Method:    getInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SimRawWrapper_getInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SimRawWrapper
 * Method:    getLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_SimRawWrapper_getLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SimRawWrapper
 * Method:    getBigInt
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_SimRawWrapper_getBigInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SimRawWrapper
 * Method:    setInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_SimRawWrapper_setInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     SimRawWrapper
 * Method:    setLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_SimRawWrapper_setLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     SimRawWrapper
 * Method:    setBigInt
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_SimRawWrapper_setBigInt
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     SimRawWrapper
 * Method:    eval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SimRawWrapper_eval
  (JNIEnv *, jobject);

/*
 * Class:     SimRawWrapper
 * Method:    sleep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SimRawWrapper_sleep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SimRawWrapper
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SimRawWrapper_end
  (JNIEnv *, jobject);

/*
 * Class:     SimRawWrapper
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SimRawWrapper_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
